In [1]:
import os
import pandas as pd
from src.path import OptionPath

# 讀取並顯示前五筆資料
df_preview = pd.read_parquet(os.path.join(OptionPath.IVS, 'option_ivs_crsp_2020.parquet'))
df_preview.head()

,secid,permno,opt_date,days,delta,impl_volatility,crsp_date,crsp_monthly_return,market_cap,size_group,is_non_micro
0,106500,10026,2020-01-31,182,-30,0.294434,2020-01-01,-0.100017,3137527.0,Large,True
1,106500,10026,2020-01-31,182,-35,0.289994,2020-01-01,-0.100017,3137527.0,Large,True
2,106500,10026,2020-01-31,182,-40,0.269747,2020-01-01,-0.100017,3137527.0,Large,True
3,106500,10026,2020-01-31,182,-45,0.245570,2020-01-01,-0.100017,3137527.0,Large,True
4,106500,10026,2020-01-31,182,-50,0.241091,2020-01-01,-0.100017,3137527.0,Large,True

In [2]:
df_preview[df_preview['is_non_micro'] == False]

,secid,permno,opt_date,days,delta,impl_volatility,crsp_date,crsp_monthly_return,market_cap,size_group,is_non_micro
1260,143585,10158,2020-01-31,91,40,0.365030,2020-01-01,0.096572,557143.250000,Micro,False
1261,143585,10158,2020-01-31,91,35,0.368460,2020-01-01,0.096572,557143.250000,Micro,False
1262,143585,10158,2020-01-31,91,30,0.379065,2020-01-01,0.096572,557143.250000,Micro,False
1263,143585,10158,2020-01-31,91,25,0.388620,2020-01-01,0.096572,557143.250000,Micro,False
1264,143585,10158,2020-01-31,91,20,0.398740,2020-01-01,0.096572,557143.250000,Micro,False
...,...,...,...,...,...,...,...,...,...,...,...
131575,143076,93434,2020-12-31,730,-25,0.852847,2020-12-01,0.122605,100103.453125,Micro,False
131576,143076,93434,2020-12-31,730,-20,0.852847,2020-12-01,0.122605,100103.453125,Micro,False
131577,143076,93434,2020-12-31,730,-15,0.852847,2020-12-01,0.122605,100103.453125,Micro,False
131578,143076,93434,2020-12-31,730,10,1.092425,2020-12-01,0.122605,100103.453125,Micro,False
131579,143076,93434,2020-12-31,730,-10,0.852847,2020-12-01,0.122605,100103.453125,Micro,False